### ISSUE TITLE
replacing &lt; &gt; pair into unicode left and right angle brackets 

### ISSUE THREAD

**Issue by mingshey** [helmadik/LSJLogeion#1]
Is it okay to replace `&lt;` and `&gt;` pair(&lt;...&gt;, used for angle brackets) into unicode left and right angle brackets( ⟨...⟩ )? It will distinguish angle brackets from etymological relation sign(&lt;,  which is the same as the less -than sign) in appearance.
I'm testing it with my local copy of grc.lsj.xml coming with Diogenes software; I've search-and-replaced them and hand-trimming to leave out isolated `&lt;`s that are etymology relations.
Before I go fork and commit, I'd like to know if it is against the encoding standards of Logeion or PDL.

**Comment by helmadik** [comment]
Please don't make this change. This sgml symbol should replaced with angled brackets at the front end, but during processing it won't be mistaken for an xml tag. 
PS - assume Peter Heslin will be handling this for Diogenes.
