### ISSUE TITLE
Entries with duplicate headwords and/or keys

### ISSUE THREAD

**Issue by ArmorBearer** [helmadik/LSJLogeion#10]
I used the following XPath expression to extract a list of the headwords:  `/tei.2/text/div1/div2/headword`  (Note that I have already changed `<head>` to `<headword>`, as discussed in [another issue](https://github.com/helmadik/LSJLogeion/issues/4).)

This produced a list of 116,471 headwords.  In this list, I found 672 duplicates, using this search criteria:

Regular Expression:  `<entry>([\w-]+)</entry>\n\s*<entry>\1</entry>`

This, in itself, is not a problem as much as a challenge.  Many dictionaries are designed to keep these 'homograph' entries together; many others are designed to allow for separate entries for homographs, as we discussed in the above linked issue.

In the latter case, some dictionaries use 'homograph numbers' to keep them separate.  For online dictionaries, this helps immensely, so that the headwords can be used as unique indexes to the entries.

In the LSJ data, I see the 'key' attribute on the `<div2>` elements.  I had assumed that this 'key' could be used as a unique index.  To make use of it, we would need to replace our direct-link from headword to entry with a level of indirection:  headword > key > entry.  And this would require that duplicate headwords would be shown in the index, but, unseen by the user, each headword would be associated with a unique key, and this key would be used to find the correct entry.

This is doable (and seems to have been done for the online Perseus dictionary).

However, I have encountered another related issue, which may be a real problem:  duplicate keys.

I used the following XPath expression to extract a list of the keys:  `/tei.2/text/div1/div2/@key`

This produced a list of 116,474 keys.  (Not sure why this number is different from the number of headwords!)  In this list, I found 23 duplicates, using this search criteria:

Regular Expression:  `key="([^"]+)"\n key="\1"`

One example is the key 'ai)go/keras'.  The first entry has the headword 'αἰγόκερας'; the second entry has the headword 'αἰγοκερεύς'.  I notice that the online Perseus dictionary only seems to show the first of these, as does my Kindle version of the print dictionary.

Another example is the key 'a)mfeleli/zw'.  This occurs 3 times, with headwords, 'ἀμφελελίζω', 'ἀμφελικτός' and 'ἀμφελίσσω'.  Again, only the first of these 3 entries can be seen in both the Kindle version and the online Perseus version.

Are these intentional, or mistakes?

Perhaps we should use the 'orig_id' attribute, rather than the 'key'...?  

Here, again, I find the number is different:
* 116,471 headwords
* 116,474 keys
* 116,473 orig_ids

*(At the moment I'm having difficulty finding the entry which contains a key, but no orig_id...)*

**Comment by helmadik** [comment]
You may be interested in https://eumaeus.github.io/2018/11/14/validating.html and other work by Chris Blackwell that you can find thereabouts. 
The original Perseus version merged many entries which I split (to make aigokereus easy to find, for instance). But in going through the entire dictionary, I clearly didn't always follow my rule of renumbering the id and certainly not redoing the betacode, which we are not using. So the orig id is your best bet, and I appreciate error reports.

**Comment by helmadik** [comment]
For the record, duplicate id-s found at 4097a , 62018, 62218. There are now 116506 id-s and 116509 heads, the difference being made up by the multiple an-s squished into one entry.
