### ISSUE TITLE
Inconsistent use of XML for identifying entries

### ISSUE THREAD

**Issue by ArmorBearer** [helmadik/LSJLogeion#12]
Most entries are of the form:
```
<div2 id="crosse)pau/+sas" orig_id="n38392" key="e)pau/+sas" type="main" opt="n">
    <headword extent="full" lang="greek" opt="n" orth_orig="ἐπαΰσας">ἐπαΰσας</headword>
```
But there are 2 that are different:
```
<div2 id="e)pauri/skw">
    <headword extent="full" lang="greek" opt="n" orth_orig="ἐπαυρίσκω">ἐπαυρίσκω</headword>
    ...
<div2 id="tomh/" orig_id="n104250a" key="tomh/" type="main" opt="n">
    <headword extent="suff" lang="greek" opt="n" orth_orig="τομ-ή">τομή</headword>
```
These 2 do not have "cross" as the prefix to the id, and the first is lacking a key attribute!  Neither of these entries is reachable in the online Perseus lexicon or in the Kindle version of the "Middle Liddell".

I have tried to correct these in my local copy of the data, but I mention it here for the benefit of others.

**Comment by helmadik** [comment]
So these are likely early cases of entries I added (or rather, entries
mistakenly merged in the original process of preparing the OCR at Perseus
(from which the Kindle version clearly took its data even if it doesn't
acknowledge that), and I wasn't always 100% awake while slogging through!
Thanks.

Helma Dik
Department of Classics
University of Chicago

**Comment by helmadik** [comment]
Thanks again. Made corrections; I have also found some of the missing/duplicate numbers: n4097a, 62018, 62218. Will upload.
