### ISSUE TITLE
Plutarch References for the Moralia do not tally with the Perseus URNs 

### ISSUE THREAD

**Issue by jacknoutch** [helmadik/LSJLogeion#14]
### Issue

LSJ uses the Stephanus pagination without title of the work for Plutarch's _Moralia_. Typically references will be something like:
`<author>Plu.</author> 2.345a`. (The `2.` is because LSJ used Wyttenbach's two volume edition of the _Moralia_. It is superfluous information for these purposes.)

These references do not tally with the Perseus URNs of the form `Perseus:abo:tlg,0007,087,345a`.

### Aim

Each reference to Plutarch's _Moralia_ should be wrapped in a `<bibl n=Perseus:abo:tlg,0007,087,345a>` tag.

---

NB @helmadik, after your email of 16 Sep, I'm writing this up as a GitHub issue since I think it will be easier for communication. Just got started on the problem yesterday :)

**Comment by helmadik** [comment]
Hi yes writing from the car rental line! The precise work # can be found in
the Diogenes listings for different pages.

**Comment by jacknoutch** [comment]
### Progress

I think I've cracked the larger part of this one! I've added 5,301 references to Plutarch's _Moralia_ across all of LSJ.

First I and added `<author>` tags to all the `Id.` references using simple regex. This makes it much easier to navigate between the references by XML - XML navigation of the files is preferable to regex, since we wish to, for example, include those `Id.` references which come directly after an `<author>` tag with text of `Plu.`.

I've made an assumption that all relevant references are in the tail of an `<author>` element. This seems sturdy for now and if I've made a mistake, then I'm undercounting the number of instances. This allows the possibility of clean up at another stage.

I've then written a script to find all the `<author>` elements which refer to Plutarch (whether their text is `Plu.` or `Id.`) and then catalogue the number of references in the tail of each element.

(One element can have multiple references, e.g. `<author>Plu.</author> 2.345a, 123b, 456c`.)

The script then wraps each of these reference with the desired `<bibl>` element in the desired format: `<bibl n=Perseus:abo:tlg,0007,087,345a>`.

NB This means the new `<bibl>` elements do not have the `<author>` elements as their children, or any other children. This is unlike most other references, but it's justified when there stephanus numbers are often the only explicit reference to the work.

The script is in my repository [LSJLogeion_tools](https://github.com/jacknoutch/LSJLogeion_tools).

### Outstanding tasks

- [x] Some spot checking for quality assurance
- [x] Some lightweight testing to give us some confidence that the script is doing what it should
- [x] Cleaning the code with comments etc. to make it more readable
- [x] Search for _Moralia_ references _not_ in the tail of `<author>` tags
- [ ] Certain references are of the "loc. cit." category (`<author>Plu</author> l.c.`). It might be that these are of a different category altogether (perhaps not just the _Moralia_). But if they are, then they should be few enough that they can be most easily amended by hand.
- [ ] Submit the pull request

**Comment by jacknoutch** [comment]
It's taken me a while to find time to do some of the post-investigatory work, testing, and write-up. But I'm happy that this is in a place that it can do some good even if it's not perfect.

The main thing is I'm confident that the LSJ text going into these scripts is the same as the text coming out.

The [README](https://github.com/jacknoutch/LSJLogeion_tools/blob/main/README.md) for the scripts explains the current situation.

**Would you like to run the scripts yourself on the LSJLogeion repository XML files, or shall I do that and send a pull request?**

## Remaining issues
As per the [README](https://github.com/jacknoutch/LSJLogeion_tools/blob/main/README.md), there are some improvements to be made at some point:

> The assumption for the add_moralia_refences tag is not quite correct: not all references to the Moralia are in the tail of <author> tags referring to Plutarch. Some appear in the tails of `<cit>` and `<sense>` tags. Particularly, there are occurences after `ib.` or `cf.`, which are often references in proper Stephanus (not Wyttenbach) format (so 123b rather than 2.123b). Further investigation should be done to see where else references may be hiding!


Testing could also be more rigorous.

**Comment by jacknoutch** [comment]
PS: As per previous discussion, we'll leave the `loc. cit.` references for another task.

**Comment by jacknoutch** [comment]
One more task to complete:

- [ ] Include `<title>` tags (e.g. `<title>[Tranq.]</title>`) for references as appropriate

**Comment by helmadik** [comment]
After some clean-up of faulty data (''Plu. 59 of'' for 590f and such), this is very close to being done! I have pulled the author tags into the bibl tags, where applicable. There were some non-Moralia works with missing bibl-s; in as far as these are still recognized as works by Plutarch (and I can locate the citations!), I've now taken care of these.

**Comment by jacknoutch** [comment]
I've rewritten the scripts to search for references in *all* elements, not just `<author>` elements. This has found another 330 references, which seem to be the ones I have referred to above, where they usually exist in the tails of `<sense>` elements and are often following an `ib.` or `cf.`.

So far the new scripts have been rather hacked together, so it needs tidying and double-checking.

I also need to check my earlier observation re: references in the tails of `<cit>` elements, as I have not come across these again in the latest runs...

**Comment by jacknoutch** [comment]
*Some progress at last. I'm sorry this wasn't in time for the new mobile app - a combination of wishing for needing more time for these projects and it being more complicated solving than I expected!*

Since the last update, I realised that my previous script was overcounting the instances requiring to be wrapped in new `<bibl>` elements for two reasons:
1. Some references look like (to regex matching) stephanus numbers, but they are for inscriptions. All such examples I found were in the tails of `<title>` tags, and there were no true instances in these circumstances, so I have written the script to ignore `<title>` tags. All others (including `<sense>`, `<cit>` etc.) are searched.
2. The method of traversal through the XML wasn't correct for my attack. Essentially, sometimes `<author>` tags which came before a reference in the text of the lexicon were checked after the reference in question. This has now been fixed.

One thing I have not managed to do yet is to include the <title> tags as per my comment:

> One more task to complete:
> 
> * [ ]  Include `<title>` tags (e.g. `<title>[Tranq.]</title>`) for references as appropriate

The only barrier is knowing what abbreviations we are using! If you let me know/point me to a comprehensive list, then I should be able to add these relatively simply.

Finally, having synced my LSJ with your latest commit, I was able to find and wrap 264 references. These are listed in [data/new_elements_2024_03_10.txt](https://github.com/jacknoutch/LSJLogeion_tools/blob/main/data/new_elements_2024_03_10.txt) if you'd like to look through them. You should be able to get the same result (without quite the amount of console-printed material) by running `python main.py etc. etc.` as per the README.

**Comment by jacknoutch** [comment]
We may also want to add the *Moralia* titles to [the abbreviations page](https://[logeion.uchicago.edu/abbreviations/lsj](https://logeion.uchicago.edu/abbreviations/lsj)) 😃

**Comment by helmadik** [comment]
Wow! And welcome back - don't apologize for having a life and a job! Will
round up the abbreviations from the Brill-Montanari bibliography

Helma Dik
Department of Classics
University of Chicago

**Comment by helmadik** [comment]
Ah, I sent the abbreviations in October, but am attaching them here. Some edge cases near the bottom of the file, you may want to clean that up before using it in a script. Basic format: worknumber tab page range tab abbreviation tab full title (and more)
[Moraliabbrevs.txt](https://github.com/helmadik/LSJLogeion/files/14551221/Moraliabbrevs.txt)
Also refreshing LSJ on github in a few moments. I notice I hadn't in a while!

**Comment by helmadik** [comment]
PS!!! I agree about leaving out the [] brackets! Will apologize to the persnickety crowd as needed.

**Comment by jacknoutch** [comment]
Thanks! I thought I'd looked through previous correspondence, so my bad, and thanks for pointing me to it again. I'll add those on soon!

**Comment by jacknoutch** [comment]
Just reporting a little progress...

I've now written a script which appears to work to populate *Moralia* `<bibl>` elements with their respective `<title>` tags. I say "appears" because the script has added several thousand such titles, and I'm nervous that it has overcompensated. I think I've cut it back slightly to prevent repeat `<title>` tags with references that are next to each other, but it still needs checking over.

Incidental to writing this script was also doing some error checking. Now that we have most all of the *Moralia* references identified, part of the new code looks over to see if there are any errors between the "n" attribute of the bibl tags (on which the hyperlinking is based) and the text itself. So, e.g., is the stephanus reference the same in each case? Does it identify the correct work within the *Moralia*, etc.

So, anyway, just wanted to say progress is being made. Following some refactoring and testing of the results, we should be good to go.

**Comment by helmadik** [comment]
I think this could well be correct. We have 15,298 (slightly down from before this morning's Thomas Magister issue) tlg,0007 instances. Of course any number of those are the old Lives for which we did have titles, so you'd want to do a more careful search for the range of work numbers but I wouldn't worry about associating them with the tlg0007  bibl tags: All it does is make errors easier to find by other users:-)

**Comment by helmadik** [comment]
Compare this ancient error in the data where in fact Moeris is cited without being recognized, after a Plutarch citation. Not your script. (I'm killing these, obviously).
<bibl n="Perseus:abo:tlg,0007,049:p.74">p.74</bibl>

**Comment by helmadik** [comment]
``<author>Plu.</author> <title>Pyrrh.</title> 11</bibl></cit>, <bibl default="NO">2.213e</bibl>``
@jacknoutch An uncaught reference. I now know how I can make this work with your script, but just so you know. And a reminder for myself.

**Comment by helmadik** [comment]
15,273 Plutarch left. I've eliminated ``([A-Z][a-z][a-z][a-z]+?\.) (<bibl n="Perseus:abo:tlg,[^>]+?>)`` cases where Hsch and Plut are the purported authors, but this is a work in progress for other authors.

**Comment by jacknoutch** [comment]
Thanks for your points above which have given me some encouragement that the new script isn't madly out of kilter.

I've gone through the code again and it seems to be working well with the corpus. Feel free to give it a go with `python main.py amend [source] [destination]` - and note that the file structure has changed so you may need to make sure your in the right place (probably within the `lsj_logeion_tools` folder. My output told me there were 5950 new edits (not just new `<title>` elements but also corrections of the "n" references in the `<bibl>` tags.)

NB I've set the new `<title>` tags to include square brackets for now, as I don't think others have been removed, and wasn't sure if you wanted to think about this more. In any case, it will be a very easy fix.

I'm hoping that we will be able to declare victory on this issue soon!

**Comment by helmadik** [comment]
@jacknoutch 🎉🎉🎉 Would you like to close the issue?

**Comment by jacknoutch** [comment]
With pleasure! 😄 

Thank you for your openness, interest, encouragement, and availability - I've enjoyed working on this with you, and will be happy to work some more on the project.

**Comment by helmadik** [comment]
See now social media😇

Helma Dik
Department of Classics
University of Chicago
