### ISSUE TITLE
Please add a license or a CC0 dedication

### ISSUE THREAD

**Issue by jonathanrobie** [helmadik/LSJLogeion#21]
This repository does not contain a license, which means I can't use it in some projects.

Could you please add either a Creative Commons license or a CC0 or something like that in a file called LICENSE.md?  For instance:

> This work is licensed under [Creative Commons Attribution-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1)

Or:

> This work is dedicated to the Public Domain under [CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/) 

There are, of course, other options.  But a clear license makes it possible to convince our lawyers to let us use this ...

**Comment by helmadik** [comment]
Many thanks for the suggestion and making it super easy to implement (if I somehow still got it wrong, please tell me - else feel free to close the issue)! Let me know where you end up using it! And please send corrections my way. Have actually just been making a bunch of NT citation corrections this morning..

**Comment by jonathanrobie** [comment]
Perfect!  Thanks!
