### ISSUE TITLE
Seemingly inconsistent use of square brackets in headwords

### ISSUE THREAD

**Issue by ArmorBearer** [helmadik/LSJLogeion#5]
I have encountered 15 occurrences of headwords containing square brackets.  Here are a few examples:
```
<head extent="full" lang="greek" opt="n" orth_orig="τεσσερᾰκαιεβδο[μη]κοντούτης">τεσσερακαιεβδο[μη]κοντούτης</head>
<head extent="suff" lang="greek" opt="n" orth_orig="σκολῐό-δ[ειρ]ος">σκολιόδ[ειρ]ος</head>
<head extent="full" lang="greek" opt="n" orth_orig="ῥηξί-[ζῠγ]ος">ῥηξί[ζυγ]ος</head>
<head extent="full" lang="greek" opt="n" orth_orig="ἀπόλυγμα[τος]·">ἀπόλυγμα[τος]</head>
```
But then I saw one occurrence where the closing square bracket was after the end head tag:

`<head extent="full" lang="greek" opt="n" orth_orig="οὐλομέτ[ριον">οὐλομέτ[ριον</head>], ...`

And then there are a few cases like these, where there is only one square bracket:
```
<head extent="full" lang="greek" opt="n" orth_orig="προεδικ[ός">προεδικ[ός</head>
<head extent="full" lang="greek" opt="n" orth_orig="τρῐσατ]ῠχής">τρισατ]υχής</head>
```

Given that these are so few in number, and the appearance of the brackets is inconsistent, I wondered if these might be typographical errors...?

**Comment by helmadik** [comment]
![image](https://user-images.githubusercontent.com/7517297/118290238-d156f680-b49b-11eb-8677-2c8028fa0a73.png)
It's trying to represent what's in the printed LSJ.

**Comment by helmadik** [comment]
![image](https://user-images.githubusercontent.com/7517297/118290347-f77c9680-b49b-11eb-9d6c-396270d1b09b.png)
It's trying to represent what's in the printed LSJ - please do report if you find cases where this is not true.

**Comment by ArmorBearer** [comment]
@helmadik, my primary issue is not that there are square brackets, but the inconsistency of their use, especially when the opening or closing bracket is missing or placed outside of the tag, as with:

`<head extent="full" lang="greek" opt="n" orth_orig="οὐλομέτ[ριον">οὐλομέτ[ριον</head>], ...`

The printed LSJ does not contain XML tags, so the placement of the closing bracket here is not a reflection of the printed LSJ.

Any comments about this?

If the opening or closing bracket is completely missing in the printed LSJ, that's another issue, and I can understand your hesitancy to depart from what is printed.  But if Jones boldly improved on Liddell-Scott's work, perhaps you should feel free, as well...?  : )

**Comment by helmadik** [comment]
Hi, I am really grateful when you report the instances where the XML does _not_ represent what's in LSJ. But the first one I checked simply had what the print ed. has. If you find more individual instances where the XML doesn't agree with the print ed., as may or may not be the case with oulometrion, do report here or in Logeion problem reports and I'll happily repair.

**Comment by ArmorBearer** [comment]
I have fixed (in our local copy) the problem where the closing square bracket was after the end head tag, of which there were ~5 occurrences.  For the benefit of those who come after me, here are the specifics of how I did the search and replace using Regular Expressions:

Search Expression: `</headword>]`
Replacement Expression: `]</headword>`

This worked for me using Notepad++. Also, I had previously combined all the individual files into one, in order to make this kind of processing easier, as well as to fit in with how our tool loads XML resources.
