### ISSUE TITLE
Non-Greek punctuation within spans of Greek text

### ISSUE THREAD

**Issue by ArmorBearer** [helmadik/LSJLogeion#8]
There are a number of instances where non-Greek punctuation is included within spans of text which are labelled as Greek.  For example:

`<foreign lang="greek">ἄ-οινος, ἄ-υπνος,</foreign>`

This prevents us from turning elements tagged as `<foreign lang="greek">` into links to other entries.  To correct this, it would need to be:

`<foreign lang="greek">ἄ-οινος</foreign>, <foreign lang="greek">ἄ-υπνος</foreign>,`

Here is another troublesome example:

`[<foreign lang="greek">ῠ], <gen lang="greek" opt="n">ἡ</gen>, </foreign>`

We don't, yet, have a solution for this.

**Comment by helmadik** [comment]
I have nothing to contribute here, I'm sorry.
