### ISSUE TITLE
Unmarked occurrence of Greek text

### ISSUE THREAD

**Issue by ArmorBearer** [helmadik/LSJLogeion#9]
I found this in the entry for 'ἄα':

`<sense n="II" id="n5.0" level="2" opt="n"> v. ἄας.</sense>`

Not marking this with `lang="greek"` prevents us from formatting this text or turning it into a link to another entry.  To correct this, it would need to be:

`<sense n="II" id="n5.0" level="2" opt="n"> v. <foreign lang="greek">ἄας</foreign>.</sense>`

I have not had the chance to search for other occurrences like this...

**Comment by helmadik** [comment]
Probably easiest to search for words in the appropriate Unicode range in order to tag them.. I've done this especially in order to include Greek words that are part of definitions of other words, where I've expanded the `<i>` tag to include them and removed foreign tags.

**Comment by ArmorBearer** [comment]
Not sure what this means...

> ... I've expanded the `<i>` tag to include them and removed foreign tags.

Does the `<i>` tag include the 'lang' attribute?  Or have you been removing express indicators of the Greek, in favor of relying on the Unicode range?  (I'm not sure I can use CSS to determine the Unicode range, so the latter would be making my life much more difficult.  Or, to put it another way, it may make it impossible for us to provide links from these cited Greek words to their respective entries.)

**Comment by helmadik** [comment]
I've often - though not consistently - changed things like 
`<i>of</i> or <i>for</i> <foreign lang="greek">βελουλκία</foreign>`
into 
`<i>of or for βελουλκία</i>`

because automatic meaning extraction left us with tons of 'of' short definitions. And yes, because Unicode works. I'll try to remember where I recently saw someone do css with Unicode ranges..
